
services:

  db:                   # usualmente escolhem este
    image: mysql:8.0   # o que roda é o 8.0.42-debian ()
    container_name: cont_mysql  #colocar nome do seu conteiner
    environment:
      MYSQL_ROOT_PASSWORD: ro0ots #escolher sua senha
      MYSQL_DATABASE: dados_mysql # esoclher nome database que quiser
      MYSQL_USER: adm             # vc escolhe
      MYSQL_PASSWORD: 12345       #vc escolhe
     
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql 
    restart: always  

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pros"]
      interval: 10s    
      timeout: 10s   
      retries: 5   
  app:     
    build: .
    ports:
      - "5002:5002"  #pegar sua porta do app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  # nome da linha 4
      DB_PORT: 3306
      DB_NAME: dados_mysql  # linha 9
      DB_USER: adm
      DB_PASSWORD: 12345

  # ------------ volume --------------

volumes:
    mysql_data:



  ##########################################################
  #                                                        #
  #                  comandos terminal                     #
  #                                                        #
  # ORDEM DA CRIAÇÃO DA IMAGE                              #
  # TODOS CONTÊINER                                        #
  # ENTRAR NO MYSQL PARA CRUED                             #
  #                                                        #
  #             docker build -t nomeImagem .               #
  #                docker-compose up -d                    #
  #     docker exec -it cont_mysql mysql -u adm -p         #
  #                                                        #
  ##########################################################

