
services:

  db:      
    image: mysql:8.0   
    container_name: cont_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ro0ots 
      MYSQL_DATABASE: dados_mysql s
      MYSQL_USER: adm 
      MYSQL_PASSWORD: 12345 
      #TZ: America/São Paulo     # time zone, isso tem haver com aws 
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql 
    restart: always  

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pros"]
      interval: 10s     
      timeout: 10s   
      retries: 5    

  app:
    build: .
    ports:
      - "5002:5002"  
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  
      DB_PORT: 3306
      DB_NAME: dados_mysql
      DB_USER: adm
      DB_PASSWORD: 12345

volumes:
    mysql_data:

  ##########################################################
  #                                                        #
  #                  comandos terminal                     #
  #                                                        #
  #######################################################


# _______________rodar tudo - compose ____________________ #

# docker-compose up -d


# _______________acessar myql-contêiner___________________ #

# docker exec -it cont_mysql mysql -u adm -p