services:
# Banco de Dados
  db:
    image: mysql:8.0 
    restart: always
    container_name: cont_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: SistemaEscolar
      MYSQL_USER: adm # Ajustar
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" # Diferente
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u adm -p12345"]
      interval: 10s
      timeout: 5s
      retries: 5

# Minha Api
  api: 
    build: .
    ports:
      - 5002:5002
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  # Nome do serviço MySQL no compose
      DB_PORT: 3306
      DB_NAME: SistemaEscolar
      DB_USER: adm
      DB_PASSWORD: 12345

volumes:
  mysql_data: {}